# Generated by Django 5.0.2 on 2024-03-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startInstructions', models.CharField(max_length=100)),
                ('finalText', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('places', models.CharField(max_length=100)),
                ('startPoint', models.CharField(max_length=100)),
                ('fires', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='QuestLongDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('keyPoints', models.CharField(max_length=100)),
                ('startPoint', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('formats', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('header', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('trueAnswers', models.CharField(max_length=100)),
                ('hints', models.CharField(blank=True, max_length=100, null=True)),
                ('historicalText', models.TextField(blank=True, null=True)),
                ('nextText', models.TextField(blank=True, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quest')),
            ],
        ),
    ]
