# Generated by Django 5.0.2 on 2024-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='name',
            field=models.CharField(default='Quest', max_length=100),
        ),
    ]
