# Generated by Django 5.0.2 on 2024-03-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questdescription',
            name='quest_long_description',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.questlongdescription'),
        ),
    ]
