# Generated by Django 5.0.2 on 2024-04-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questdescription_quest_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='finalText',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quest',
            name='startInstructions',
            field=models.CharField(max_length=1000),
        ),
    ]
