# Generated by Django 5.0.2 on 2024-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
