# Generated by Django 5.0.2 on 2024-04-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_question_additional_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
